### ISSUE TITLE
[Bug] Getting a "ValueError: Unknown Encoding: �)0�" error when running hello world sample app

### ISSUE THREAD

**Issue by vkarpov15** [temporalio/sdk-node#110]
**Describe the bug**

**To Reproduce**
1. Go to https://docs.temporal.io/docs/node/getting-started/
2. Follow steps
3. Get below error when running `node lib/worker/schedule-workflow.js`:

```
2021-05-25T22:02:48.562Z [INFO] webpack 5.37.1 compiled successfully in 744 ms
2021-05-25T22:02:48.696Z [INFO] Worker state changed { state: 'RUNNING' }
2021-05-25T22:02:51.942Z [ERROR] Worker failed {
  error: ValueError: Unknown encoding: �)0�
      at CompositeDataConverter.fromPayload (/home/val/Workspace/temporalio/example/node_modules/@temporalio/workflow/lib/converter/data-converter.js:29:19)
      at /home/val/Workspace/temporalio/example/node_modules/@temporalio/workflow/lib/converter/data-converter.js:54:47
      at Array.map (<anonymous>)
      at Object.arrayFromPayloads (/home/val/Workspace/temporalio/example/node_modules/@temporalio/workflow/lib/converter/data-converter.js:54:20)
      at /home/val/Workspace/temporalio/example/node_modules/@temporalio/worker/lib/worker.js:303:55
      at rxjs_1.pipe.operators_1.mergeScan.state (/home/val/Workspace/temporalio/example/node_modules/@temporalio/worker/lib/rxutils.js:15:68)
      at MergeScanSubscriber._next (/home/val/Workspace/temporalio/example/node_modules/rxjs/internal/operators/mergeScan.js:55:23)
      at MergeScanSubscriber.Subscriber.next (/home/val/Workspace/temporalio/example/node_modules/rxjs/internal/Subscriber.js:66:18)
      at Subject.next (/home/val/Workspace/temporalio/example/node_modules/rxjs/internal/Subject.js:60:25)
      at GroupBySubscriber._group (/home/val/Workspace/temporalio/example/node_modules/rxjs/internal/operators/groupBy.js:98:19)
}
2021-05-25T22:02:51.943Z [INFO] Worker state changed { state: 'FAILED' }
  May 25 18:02:51.943  WARNtemporal_sdk_core::workflow::concurrency_manager: Sending side of workflow machine creator was dropped. Likely the WorkflowConcurrencyManager was dropped. This indicates a failure to call shutdown.

```

**Expected behavior**

No error

**Screenshots/Terminal ouput**
If applicable, add screenshots or code blocks to help explain your problem. You can also use [Loom](http://loom.com/) to do short, free video bug reports.

![image](https://user-images.githubusercontent.com/1620265/119574933-3952ea00-bd84-11eb-8a9a-eda734016a2b.png)

**Versions (please complete the following information where relevant):**
 - OS: [e.g. Mac, Windows, Linux]
 - Temporal Version [e.g. 1.7.0?]
 - are you using Docker or Kubernetes or building Temporal from source?

Xubuntu 18.04, Node v14.4.0, [@temporalio/create](https://www.npmjs.com/package/@temporalio/create) v0.3.0

**Additional context**

**Comment by vkarpov15** [comment]
This problem goes away when I change task queue names, so I think it may be due to an old entry in the task queue causing issues.

**Comment by bergundy** [comment]
Sounds like you figured out the issue.
You can verify by listing open Workflows on you Temporal server and finding one that uses the default namespace and the tutorial task queue.
If you change the Worker [log level](https://docs.temporal.io/docs/node/logging/) to `DEBUG` you might find out some more information too.
We can definitely improve the error message and probably should prevent this sort of error from killing the Worker.

**Comment by bergundy** [comment]
TBH, I don't think we can improve the error message much, looks like the Payload metadata contains non-unicode characters https://github.com/temporalio/sdk-node/blob/a25c0feca791a195eb5e50cf8c0fd9e0b5a1db83/packages/workflow/src/converter/data-converter.ts#L65

**Comment by sw-yx** [comment]
use temporal, unleash cthulu!

**Comment by bergundy** [comment]
@vkarpov15 can we close this?
