### ISSUE TITLE
[Bug] 14 UNAVAILABLE error against Cloud deployment

### ISSUE THREAD

**Issue by jmoseley** [temporalio/sdk-node#117]
**Describe the bug**
When executing RPC requests against the cloud deployment, we receive an error `14 UNAVAILABLE: Connection dropped`.

```
Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/atlas-event-service/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/atlas-event-service/node_modules/@grpc/grpc-js/src/client.ts:338:36)
    at Object.onReceiveStatus (/atlas-event-service/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
    at Object.onReceiveStatus (/atlas-event-service/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
    at /atlas-event-service/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**To Reproduce**
I am unable to reproduce this error running the same code against a local service.

**Expected behavior**
I expect the RPC call to succeed.

**Versions (please complete the following information where relevant):**
 - OS: Linux
 - Temporal Version: Cloud
 - Node SDK version: 0.3.0

**Additional context**
* Before executing the RPC call, I first call `untilReady` to ensure that the gRPC client is connected, and this succeeds.
* When I receive this error, I close the connection, open a new connection (call `untilReady` again), and retry the call. It fails with the same error.
* I have also configured keep alive checks to ensure the connection does not go stale.

Here is some sample code:

```
export class TemporalClientImpl implements TemporalClient {
  // This is assigned in createConnection.
  private connection!: Connection;
  private ready = false;
  private log: ReturnType<typeof newLogger>;

  private untilReadyPromise: Promise<void> | undefined = undefined;

  constructor(
    private options: {
      address: string;
      credentials: grpc.ChannelCredentials;
      namespace: string;
    },
  ) {
    this.log = newLogger(this.constructor.name);
    this.createConnection();
  }

  private createConnection() {
    this.connection = new Connection({
      address: this.options.address,
      credentials: this.options.credentials,
      channelArgs: {
        'grpc.keepalive_time_ms': TEMPORAL_KEEP_ALIVE_INTERVAL_MS,
        'grpc.keepalive_permit_without_calls': 1,
        'grpc.keepalive_timeout_ms': TEMPORAL_KEEP_ALIVE_TIMEOUT_MS,
      },
    });
  }

  private async reconnect() {
    this.ready = false;
    if (this.connection) {
      try {
        this.connection.client.close();
      } catch (error) {
        this.log.error('Error closing client connection.', error);
      }
    }
    this.createConnection();

    return await this.waitForReady();
  }

  async waitForReady() {
    if (this.ready) {
      return;
    }

    if (this.untilReadyPromise) {
      return await this.untilReadyPromise;
    }

    this.untilReadyPromise = this.connection.untilReady(TEMPORAL_CONNECTION_TIMEOUT_MS);

    return this.untilReadyPromise;
  }

  async completeActivity(taskToken: string, payload: object | null, isRetry = false): Promise<void> {
    if (!this.ready) {
      await this.waitForReady();
    }

    try {
      const req = temporal.api.workflowservice.v1.RespondActivityTaskCompletedRequest.fromObject({
        taskToken,
        namespace: this.options.namespace,
        result: {
          payloads: this.connection.options.dataConverter.toPayloads(JSON.stringify(payload)),
        },
      });

      await this.connection.service.respondActivityTaskCompleted(req);

      this.log.info(`Successfully completed activity task.`);
    } catch (error) {
      if (error.message.includes('workflow execution already completed')) {
        throw new ActivityAlreadyCompleteError(taskToken);
      }

      if (error.message.includes('invalid activityID')) {
        throw new ActivityNotFoundError(taskToken);
      }

      if (error.details && error.details.includes('Connection dropped')) {
        this.log.error('Received connection dropped error, attempting to reconnect.');
        await this.reconnect();
        if (!isRetry) {
          this.log.error('Retrying call to completeActivity');
          return await this.completeActivity(taskToken, payload, true);
        }
      }

      this.log.info('Unknown RPC error', error);

      throw error;
    }
  }
}
```

**Comment by jmoseley** [comment]
I was eventually able to solve this by switching from using `grpc.Credentials` to use `TLSConfig` for specifying the TLS certs:

Before:
```
let grpcCredentials: grpc.ChannelCredentials = grpc.credentials.createInsecure();
if (temporalConfig.clientCert && temporalConfig.clientCertKey) {
  // The secrets manager encodes the new lines, so unencode them to make these valid PEM
  const cert = temporalConfig.clientCert.replace(/\\n/g, '\n');
  const certKey = temporalConfig.clientCertKey.replace(/\\n/g, '\n');
  const rootCa = temporalConfig.rootCa
    ? Buffer.from(temporalConfig.rootCa.replace(/\\n/g, '\n'))
    : undefined;

  grpcCredentials = grpc.credentials.createSsl(rootCa, Buffer.from(certKey), Buffer.from(cert));
} else {
  LOG.info('No TLS configuration provided for Temporal, not using mTLS.');
}

const address = `${temporalConfig.host}:${temporalConfig.port}`;

const connection =  new Connection({
  address,
  credentials,
  channelArgs: {
    'grpc.keepalive_time_ms': TEMPORAL_KEEP_ALIVE_INTERVAL_MS,
    'grpc.keepalive_permit_without_calls': 1,
    'grpc.keepalive_timeout_ms': TEMPORAL_KEEP_ALIVE_TIMEOUT_MS,
  },
});
```

After:
```
let tlsConfig: TLSConfig | boolean = false;
if (temporalConfig.clientCert && temporalConfig.clientCertKey) {
  // The secrets manager encodes the new lines, so unencode them to make these valid PEM
  const cert = temporalConfig.clientCert.replace(/\\n/g, '\n');
  const certKey = temporalConfig.clientCertKey.replace(/\\n/g, '\n');
  const rootCa = temporalConfig.rootCa
    ? Buffer.from(temporalConfig.rootCa.replace(/\\n/g, '\n'))
    : undefined;

  tlsConfig = {
    serverRootCACertificate: rootCa,
    clientCertPair: {
      crt: Buffer.from(cert),
      key: Buffer.from(certKey),
    },
  };
} else {
  LOG.info('No TLS configuration provided for Temporal, not using mTLS.');
}

const address = `${temporalConfig.host}:${temporalConfig.port}`;

const connection = new Connection({
  address,
  tls: tlsConfig,
  channelArgs: {
    'grpc.keepalive_time_ms': TEMPORAL_KEEP_ALIVE_INTERVAL_MS,
    'grpc.keepalive_permit_without_calls': 1,
    'grpc.keepalive_timeout_ms': TEMPORAL_KEEP_ALIVE_TIMEOUT_MS,
  },
});
```
