### ISSUE TITLE
[Bug] Cannot find module 'ms'

### ISSUE THREAD

**Issue by alex-dixon** [temporalio/sdk-node#197]
### Describe the bug

Appears to happen when using @temporal/client and no other temporal libraries.

### To Reproduce
I don't have an example I can share. I'd expect a minimal example with @temporal/client only would trigger the same error.

### Screenshots/Terminal output
```
2021-08-22T15:57:32.140Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'ms'\nRequire stack:\n- /var/task/node_modules/@temporalio/workflow/lib/time.js\n- /var/task/node_modules/@temporalio/workflow/lib/internals.js\n- /var/task/node_modules/@temporalio/workflow/lib/workflow.js\n- /var/task/node_modules/@temporalio/workflow/lib/index.js\n- /var/task/node_modules/@temporalio/client/lib/workflow-client.js\n- /var/task/node_modules/@temporalio/client/lib/index.js\n- /var/task/lambdas/foo.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'ms'",
        "Require stack:",
        "- /var/task/node_modules/@temporalio/workflow/lib/time.js",
        "- /var/task/node_modules/@temporalio/workflow/lib/internals.js",
        "- /var/task/node_modules/@temporalio/workflow/lib/workflow.js",
        "- /var/task/node_modules/@temporalio/workflow/lib/index.js",
        "- /var/task/node_modules/@temporalio/client/lib/workflow-client.js",
        "- /var/task/node_modules/@temporalio/client/lib/index.js",
        "- /var/task/lambdas/foo.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

### Versions
0.5.0

**Comment by bergundy** [comment]
That's odd, I see it in the package.json for that release: https://github.com/temporalio/sdk-node/blob/fe468fc338bd4863117489547e8f7a602bb08d35/packages/client/package.json#L19

**Comment by bergundy** [comment]
I failed to reproduce this:
```shellsession
$ npm init -y
...
$ npm i @temporalio/client@0.5.0

added 33 packages, and audited 34 packages in 10s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ node
Welcome to Node.js v16.6.0.
Type ".help" for more information.
> require('@temporalio/client')
{
  defaultDataConverter: [Getter],
  defaultWorkflowClientOptions: [Getter],
  WorkflowClient: [Getter],
  QueryRejectedError: [Getter],
  WorkflowService: [Getter],
  LOCAL_DOCKER_TARGET: [Getter],
  defaultConnectionOpts: [Getter],
  Connection: [Getter],
  WorkflowExecutionTerminatedError: [Getter],
  WorkflowExecutionTimedOutError: [Getter],
  WorkflowExecutionFailedError: [Getter],
  WorkflowExecutionCancelledError: [Getter],
  WorkflowExecutionContinuedAsNewError: [Getter],
  addDefaults: [Getter],
  compileWorkflowOptions: [Getter]
}
```

Please reopen if you manage to reproduce this
