### ISSUE TITLE
[Bug] publish-to-verdaccio fails

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-node#265]
### Describe the bug

When I run `node scripts/publish-to-verdaccio.js` locally, I get `ECONNREFUSED` and it edits `packages/*/package.json`.

First run:

```
$ node scripts/publish-to-verdaccio.js --registry-dir /tmp/registry
Starting local registry
Local registry ready
Need to install the following packages:
  verdaccio
Ok to proceed? (y) ylerna notice cli v4.0.0
lerna info versioning independent
lerna WARN Unable to determine published version, assuming "@temporalio/activity" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/client" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/common" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/core-bridge" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/create" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/interceptors-opentelemetry" unpublished.
lerna WARN Unable to determine published version, assuming "temporalio" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/proto" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/worker" unpublished.
lerna WARN Unable to determine published version, assuming "@temporalio/workflow" unpublished.

Found 10 packages to publish:
 - @temporalio/activity => 0.4.0
 - @temporalio/client => 0.7.0
 - @temporalio/common => 0.3.0
 - @temporalio/core-bridge => 0.4.0
 - @temporalio/create => 0.5.1
 - @temporalio/interceptors-opentelemetry => 0.2.0
 - temporalio => 0.4.2
 - @temporalio/proto => 0.3.2
 - @temporalio/worker => 0.9.0
 - @temporalio/workflow => 0.8.0

lerna info auto-confirmed 
lerna info publish Publishing packages to npm...
lerna notice Skipping all user and access validation due to third-party registry
lerna notice Make sure you're authenticated properly ¯\_(ツ)_/¯
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @temporalio/common -> @temporalio/proto -> @temporalio/core-bridge -> @temporalio/common
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @temporalio/common -> @temporalio/proto -> @temporalio/core-bridge -> @temporalio/common
lerna ERR! ECONNREFUSED request to http://localhost:4873/@temporalio%2factivity failed, reason: connect ECONNREFUSED 127.0.0.1:4873
lerna ERR! FetchError: request to http://localhost:4873/@temporalio%2factivity failed, reason: connect ECONNREFUSED 127.0.0.1:4873
lerna ERR!     at ClientRequest.<anonymous> (/Users/me/gh/sdk-node/node_modules/minipass-fetch/lib/index.js:110:14)
lerna ERR!     at ClientRequest.emit (node:events:394:28)
lerna ERR!     at Socket.socketErrorListener (node:_http_client:447:9)
lerna ERR!     at Socket.emit (node:events:406:35)
lerna ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
lerna ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
lerna ERR! lerna request to http://localhost:4873/@temporalio%2factivity failed, reason: connect ECONNREFUSED 127.0.0.1:4873
Error: Failed to publish to registry
    at /Users/me/gh/sdk-node/scripts/publish-to-verdaccio.js:15:13
    at withRegistry (/Users/me/gh/sdk-node/scripts/registry.js:79:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/me/gh/sdk-node/scripts/publish-to-verdaccio.js:6:3)
```

Second run fails due to uncommited changes:
    
```
sdk-node git:(create-from-repo 1↑) 10M $ node scripts/publish-to-verdaccio.js --registry-dir /tmp/registry
Starting local registry
Local registry ready
Need to install the following packages:
  verdaccio
Ok to proceed? (y) lerna notice cli v4.0.0
lerna info versioning independent
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M packages/activity/package.json
lerna ERR! EUNCOMMIT  M packages/client/package.json
lerna ERR! EUNCOMMIT  M packages/common/package.json
lerna ERR! EUNCOMMIT  M packages/core-bridge/package.json
lerna ERR! EUNCOMMIT  M packages/create-project/package.json
lerna ERR! EUNCOMMIT  M packages/interceptors-opentelemetry/package.json
lerna ERR! EUNCOMMIT  M packages/meta/package.json
lerna ERR! EUNCOMMIT  M packages/proto/package.json
lerna ERR! EUNCOMMIT  M packages/worker/package.json
lerna ERR! EUNCOMMIT  M packages/workflow/package.json
Error: Failed to publish to registry
    at /Users/me/gh/sdk-node/scripts/publish-to-verdaccio.js:15:13
    at withRegistry (/Users/me/gh/sdk-node/scripts/registry.js:79:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/Users/me/gh/sdk-node/scripts/publish-to-verdaccio.js:6:3)
```

### To Reproduce

```
rm /tmp/registry/storage
npm ci
npm run rebuild
node scripts/publish-to-verdaccio.js --registry-dir /tmp/registry
```

**Comment by lorensr** [comment]
Fixed by changing `rm /tmp/registry/storage` to `rm /tmp/registry`
