### ISSUE TITLE
[Feature Request] Plan for supporting npm modules that require ESM, eg node-fetch

### ISSUE THREAD

**Issue by sw-yx** [temporalio/sdk-node#279]
### Is your feature request related to a problem? Please describe.

Right now, we have no way to support "pure ESM" node modules. our Webpack config is hardcoded to commonjs.

So @vkarpov15 found that importing `node-fetch@3` had an issue and had to downgrade to `node-fetch@2`.

over time, this will increasingly be a problem, as more and more of the Node ecosystem [goes pure ESM](https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77).

### Describe the solution you'd like

"smooth" bundling solution that addresses ESM and CJS.

**Comment by bergundy** [comment]
I wasn’t aware es modules are not supported, they should be supported in webpack and in node.
What does the error message look like?

**Comment by lorensr** [comment]
repro: https://github.com/lorensr/samples-node/tree/fetch

```
cd activities-examples
npm i
npm start
```

```
> temporal-http@0.1.0 start
> ts-node src/worker.ts

/Users/me/gh/samples-node/activities-examples/src/activities/cancellable-fetch.ts:8
  if (contentLengthHeader === null) {
                                     ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/gh/samples-node/activities-examples/node_modules/node-fetch/src/index.js from /Users/me/gh/samples-node/activities-examples/src/activities/cancellable-fetch.ts not supported.
Instead change the require of index.js in /Users/me/gh/samples-node/activities-examples/src/activities/cancellable-fetch.ts to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/src/activities/cancellable-fetch.ts:8:38)
    at Module.m._compile (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:704:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:706:16)
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/src/activities/index.ts:10:27)
    at Module.m._compile (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:704:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:706:16)
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/src/worker.ts:27:33)
    at Module.m._compile (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:704:29)
    at Object.require.extensions.<computed> [as .ts] (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/index.js:706:16)
    at main (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/bin.js:237:16)
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/node_modules/ts-node/dist/bin.js:350:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by bergundy** [comment]
Could this be a ts node issue? Did you try with node?

**Comment by lorensr** [comment]
```
$ node lib/worker.js
/Users/me/gh/samples-node/activities-examples/lib/activities/cancellable-fetch.js:8
const node_fetch_1 = __importDefault(require("node-fetch"));
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/me/gh/samples-node/activities-examples/node_modules/node-fetch/src/index.js from /Users/me/gh/samples-node/activities-examples/lib/activities/cancellable-fetch.js not supported.
Instead change the require of index.js in /Users/me/gh/samples-node/activities-examples/lib/activities/cancellable-fetch.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/lib/activities/cancellable-fetch.js:8:38)
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/lib/activities/index.js:10:27)
    at Object.<anonymous> (/Users/me/gh/samples-node/activities-examples/lib/worker.js:27:33) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by bergundy** [comment]
What happens if you just run node lib/activities.js?
If you get the same error this is probably an issue with node fetch

**Comment by bergundy** [comment]
You can also confirm by trying to import a different es module

**Comment by lorensr** [comment]
> What happens if you just run node lib/activities.js?

Same error. Got it working by having TypeScript output ESM, but that results in a new error from the worker:

repro: https://github.com/lorensr/samples-node/tree/fetch-esm


```
$ node lib/worker.js
(node:12420) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2021-10-05T17:37:34.763Z [INFO] asset main.js 4.24 KiB [emitted] (name: main)
2021-10-05T17:37:34.764Z [INFO] runtime modules 274 bytes 1 module
2021-10-05T17:37:34.764Z [INFO] ../../../../../src/main.js 704 bytes [built] [code generated]
2021-10-05T17:37:34.764Z [INFO] webpack 5.54.0 compiled successfully in 73 ms
2021-10-05T17:37:34.782Z [INFO] Worker state changed { state: 'RUNNING' }
2021-10-05T17:37:34.807Z [ERROR] Failed to activate workflow {
  runId: '1fe38040-3e24-403c-830d-3190b0ab8309',
  error: ReferenceError: require is not defined
      at eval (webpack-internal:///../../../../../src/main.js:2:13)
      at Object.../../../../../src/main.js (workflow-isolate:20:1)
      at workflow-isolate:47:60
      at workflow-isolate:50:12
      at (<isolated-vm boundary>)
      at getContext (/Users/me/gh/samples-node/activities-examples/node_modules/@temporalio/worker/lib/isolate-context-provider.js:25:22),
  workflowExists: false
}
2021-10-05T17:37:44.808Z [ERROR] Failed to activate workflow {
  runId: '1fe38040-3e24-403c-830d-3190b0ab8309',
  error: ReferenceError: require is not defined
      at eval (webpack-internal:///../../../../../src/main.js:2:13)
      at Object.../../../../../src/main.js (workflow-isolate:20:1)
      at workflow-isolate:47:60
      at workflow-isolate:50:12
      at (<isolated-vm boundary>)
      at getContext (/Users/me/gh/samples-node/activities-examples/node_modules/@temporalio/worker/lib/isolate-context-provider.js:25:22),
  workflowExists: false
}
```

**Comment by bergundy** [comment]
Interesting, webpack supports both commonjs and esm.
Looks like it's the dynamic loading that's causing these issues.

**Comment by schickling** [comment]
Running into the same problem when I've set ` "type": "module",` in my `package.json` (which is become the default for new codebases).

This will also require the following code change:

```ts
  const workflowsPath = new URL('./workflows.js', import.meta.url).toString().replace(/^file:\/\//, '')
  // const workflowsPath = require.resolve('./workflows.js') // instead of this
  const worker = await Worker.create({
    workflowsPath,
```

**Comment by bergundy** [comment]
After cleaning up, I realized it was actually pretty easy to support this.
Note that with ESM imports the [file extension is mandatory](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions) and I couldn't get it running with `ts-node`.
AFAICT this is `ts-node` support is still WIP, see https://github.com/TypeStrong/ts-node/issues/1007.

I considered supporting URLs in `workflowsPath` and `nodeModulesPaths` but I think there's not that much value in it.

```ts
const workflowsPath = new URL('./workflows.js', import.meta.url).pathname;
```

**Comment by bergundy** [comment]
No problem, better now than later :)

**Comment by lorensr** [comment]
This will be fixed in the next release, coming soon.
